Python 3.12.6 (tags/v3.12.6:a4a2d2b, Sep  6 2024, 20:11:23) [MSC v.1940 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
def add(a,b):
    return a+b
grint(add(2+3))
SyntaxError: invalid syntax
print(add(2+b))
Traceback (most recent call last):
  File "<pyshell#3>", line 1, in <module>
    print(add(2+b))
NameError: name 'add' is not defined
print(add(2+4))
Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    print(add(2+4))
NameError: name 'add' is not defined
def num(n):
    n=7
    return n

print(num(20))
7
def add(a,b):
    return a+b

print(add(2+4))
Traceback (most recent call last):
  File "<pyshell#13>", line 1, in <module>
    print(add(2+4))
TypeError: add() missing 1 required positional argument: 'b'
print(add(2,4))
6
s="rohit"
len(s)
5
def num(r):
    r=1
    return r
    print(num(r))
NameError: name 'r' is not defined
print(num(13))
1
def nums(x=4,y):
    
SyntaxError: parameter without a default follows parameter with a default
def nums(x,y=4):
    return (x,y)

print(nums(4))
(4, 4)
print(nums(15,12))
(15, 12)
print(nums(12))
(12, 4)
def cgpa(a,b):
    return(a,b)

print(cgpa(b=8.7,a=9.5))
(9.5, 8.7)
def marks(a,b,c,d):
    return(a,b,c,d)

print(marks(a=1,b=2,c=3,c=4))
SyntaxError: keyword argument repeated: c
print(marks(a,b,c,d))
Traceback (most recent call last):
  File "<pyshell#41>", line 1, in <module>
    print(marks(a,b,c,d))
NameError: name 'a' is not defined
print(marks(a=1,c=3,d=4,b=2))
(1, 2, 3, 4)
def nums(x=2,y):
    
SyntaxError: parameter without a default follows parameter with a default
def function(*args_list):
    return(args_list)

print(function(2,5,7,9))
(2, 5, 7, 9)
print(function(1,2,4,5,6,7,9,5,))
(1, 2, 4, 5, 6, 7, 9, 5)
print(function("rohit","shailee","sunny","shivani"))
('rohit', 'shailee', 'sunny', 'shivani')
def value():
    num=12
    print("value inside function:",num)

    
num=11
value()
value inside function: 12
print("value outside function:",num)
value outside function: 11
global n
n=12
def value():
    print("value inside function:",n)

    
print("In function:",value(n))
Traceback (most recent call last):
  File "<pyshell#62>", line 1, in <module>
    print("In function:",value(n))
TypeError: value() takes 0 positional arguments but 1 was given
print("In function:",value(n))
Traceback (most recent call last):
  File "<pyshell#63>", line 1, in <module>
    print("In function:",value(n))
TypeError: value() takes 0 positional arguments but 1 was given
def value(n)
SyntaxError: expected ':'

global n
n=12
def value(n)
SyntaxError: expected ':'
def value(n):
    print("In function:",value(n))

    
print("In function:",value(n))
Traceback (most recent call last):
  File "<pyshell#72>", line 1, in <module>
    print("In function:",value(n))
  File "<pyshell#71>", line 2, in value
    print("In function:",value(n))
  File "<pyshell#71>", line 2, in value
    print("In function:",value(n))
  File "<pyshell#71>", line 2, in value
    print("In function:",value(n))
  [Previous line repeated 1023 more times]
RecursionError: maximum recursion depth exceeded
>>> def value(n):
...     print("value inside function:",n)
... 
...     
>>> print("In function:",value(n))
value inside function: 12
In function: None
>>> print(n)
12
